# Generated by Django 5.2.4 on 2025-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ticked',
            field=models.BooleanField(default=False),
        ),
    ]
