# Generated by Django 5.2.4 on 2025-07-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
    ]
