# Generated by Django 5.2.4 on 2025-07-28 21:41

from django.db import migrations


def remove_duplicate_notes(apps, schema_editor):
    """Remove duplicate notes before adding unique constraint"""
    Notes = apps.get_model('api', 'Notes')
    
    # Get all notes grouped by user_id and date
    from django.db.models import Min
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Find duplicates and keep only the first one (lowest ID)
        cursor.execute("""
            DELETE FROM notes 
            WHERE id NOT IN (
                SELECT MIN(id) 
                FROM notes 
                GROUP BY user_id, date
            )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_schedule'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_notes, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('user_id', 'date')},
        ),
    ]
