# Generated by Django 5.2.4 on 2025-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_notes_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('rollover', 'Rollover'), ('initiated', 'Initiated')], default='not-started', max_length=20),
        ),
    ]
